<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\..\GymProject VMC.net\Videos\Session 06\Files\ViewModels\SessionViewModel\CreateSessionViewModel.cs" Link="ViewModels\SessionViewModel\CreateSessionViewModel.cs" />
    <Compile Include="..\..\..\..\..\GymProject VMC.net\Videos\Session 06\Files\ViewModels\SessionViewModel\SessionViewModel.cs" Link="ViewModels\SessionViewModel\SessionViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GymMangment.DAL\GymMangment.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\SessionViewModel\" />
  </ItemGroup>

</Project>
